version: '3'
services:

  neo4jv3:
    image: neo4j:3.4.0 # 3.5.5
    volumes:
      - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/mnt:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/logs:/var/lib/neo4j/logs
    restart: always
    # privileged: true
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - docker-kg
    environment:
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_AUTH=neo4j/123456  #修改默认用户密码

  redis:
    image: redis
    container_name: docker_redis
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    command:
      #      两个写入操作 只是为了解决启动后警告 可以去掉
      /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
      && echo never > /sys/kernel/mm/transparent_hugepage/enabled
      && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379

networks:
  docker-kg:
    external: true