version: '3'
services:

  neo4jv3:
    image: neo4j:3.4.0 # 3.5.5
    volumes:
      - ./neo4j/conf:/var/lib/neo4j/conf
      - ./neo4j/mnt:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
      - ./neo4j/data:/data
      - ./neo4j/logs:/var/lib/neo4j/logs
    restart: always
    # privileged: true
    ports:
      - 7474:7474
      - 7687:7687
    networks:
      - docker-kg
    environment:
      - NEO4J_dbms_memory_heap_maxSize=4G
      - NEO4J_AUTH=neo4j/123456  #修改默认用户密码

  mysql80:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - "3310:3306"
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/init-sql:/docker-entrypoint-initdb.d
    networks:
      - docker-kg
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always

  redis:
    image: redis
    container_name: docker-redis
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/logs:/logs
    command:
      #      两个写入操作 只是为了解决启动后警告 可以去掉
      /bin/bash -c "echo 511 > /proc/sys/net/core/somaxconn
      && echo never > /sys/kernel/mm/transparent_hugepage/enabled
      && redis-server /usr/local/etc/redis/redis.conf"
    ports:
      - 6379:6379
    networks:
      - docker-kg

  kg-python:
    build:
      context: ../
      dockerfile: Dockerfile.python
    container_name: kg-python
    volumes:
      - /etc/localtime:/etc/localtime
    ports:
      - 5000:5000
    depends_on:
      - neo4jv3
    networks:
      - docker-kg

  kg-java:
    build:
      context: kg-java
      dockerfile: Dockerfile
    container_name: kg-java
    ports:
      - "8012:8001"
    volumes:
      - /etc/localtime:/etc/localtime
    depends_on:
      - mysql80
    restart: always
    networks:
      - docker-kg

networks:
  docker-kg:
    external: true